#!/bin/bash

set -ef

# Helper script to ingest the phonebook from stdin and cache it for search

# Which Telstar database are we running in?
# Lowercase the environment variable to use as a parameter for telstar-util
DATABASE=${TELSTAR_DBCOLLECTION,,?}

# Where are we?
TELSTARDIR=$(dirname $(realpath $0))

# Set up the Perl environment
PERL5LIB=$TELSTARDIR/lib${PERL5LIB:+:$PERL5LIB}
export PERL5LIB

# Read the schedule from stdin and update the persistent index files
cat - > "$TELSTARDIR/volume/phonebook.json"
