#!/usr/bin/env perl

use strict;
use warnings;

use JSON::PP;
use Text::Wrapper;
use PriceListFormatter;

my $directory = "newframes";
my $filename = "on-tap.json";
my $year = 2024;
my $taplist;

if (open my $input, "<", $filename)
{
    local $/ = undef;
    $taplist = JSON::PP->new->utf8->decode(<$input>);
    close $input;
}
else
{
    die "Cannot open input $filename: $!";
}

# Ensure output directory exists
-d $directory || mkdir $directory || die "Could not create $directory/: $!";

$TelstarFrame::directory = $directory;
$TelstarFrame::service = "[R][n][C] EMF ${year}[W]Live   [-]";

my %sections = (
    "Real Ale" => $taplist->{ales},
    "Real Cider" => $taplist->{ciders},
    "Lager and Craft" => $taplist->{kegs},
);

my $header  = "[R][n][D][Y]ON TAP:[W]Pouring now, in the bar";

my $lister = new PriceListFormatter("bar",
                                    31,
                                    3,
                                    $header);

for my $section (sort keys %sections)
{
    $lister->new_section($section);
    $lister->list_items(map $_->{stocktype}, @{$sections{$section}});
}

$lister->finish();