#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Long;
use JSON::PP;
use TelstarFrame;
use POSIX qw(strftime fmod);
use Time::Piece;
use Data::Dumper;

my $filename = "ledbury-3hour.json";
my $daylist = "weather-days.json";
my $directory = "wxframes";
my $year = 2026;

GetOptions("filename=s" => \$filename,
           "year=s" => \$year,
           "directory=s" => \$directory) or die "Error in command line arguments.";

my $logical_day_start = 6;
my $first_frame_number = 61;

# Ensure output directory exists
-d $directory || mkdir $directory || die "Could not create $directory/: $!";

$TelstarFrame::directory = $directory;
$TelstarFrame::service = "[R][n][C] EMF ${year}[W]Live   [-]";

# Convert a direction in degrees to the nearest compass reading
my %directions = (
      0   => "N",
     22.5 => "NNE",
     45   => "NE",
     67.5 => "ENE",
     90   => "E",
    112.5 => "ESE",
    135   => "SE",
    157.5 => "SSE",
    180   => "S",
    202.5 => "SSW",
    225   => "SW",
    247.5 => "WSW",
    270   => "W",
    292.5 => "WNW",
    315   => "NW",
    337.5 => "NNW",
);

sub cardinal
{
    my $dir = shift;

    # Round to nearest 22.5-degree interval
    my $closest_dir = 22.5 * int(($dir + 22.4)/22.5);
    $closest_dir = fmod($closest_dir, 360);

    return $directions{$closest_dir} || "???";
}

# Start by reading the forecast from the JSON file...
my $data;

if (open my $input, "<", $filename)
{
    local $/ = undef;
    $data = JSON::PP->new->utf8->decode(<$input>);
    close $input;
}
else
{
    die "Cannot open input $filename: $!";
}

# Make sure it's what we expect it to be
die "Unexpected data type $data->{type}" unless
    $data->{type} eq "FeatureCollection";

die "Unexpected location $data->{features}->[0]->{properties}->{location}->{name}" unless
    $data->{features}->[0]->{properties}->{location}->{name} eq "Ledbury";

my %param_units = ();
while (my ($name, $param) = each %{$data->{parameters}->[0]})
{
    $param_units{$name} = $param->{unit}->{symbol}->{type};
}

my %expected_units = (
    feelsLikeTemp => "Cel",
    screenRelativeHumidity => "%",
    maxScreenAirTemp => "Cel",
    windDirectionFrom10m => "deg",
    windSpeed10m => "m/s", # TODO
    uvIndex => "1",
    significantWeatherCode => "1",
    probOfPrecipitation => "%",
);

for (keys %expected_units)
{
    die "Unexpected unit $param_units{$_} for parameter $_" unless
        $param_units{$_} eq $expected_units{$_};
}

# Pull out the time the forecast was made
my $updated_str = $data->{features}->[0]->{properties}->{modelRunDate};
my $updated_utc = Time::Piece->strptime($updated_str, "%FT%H:%MZ");
my $updated_local = localtime($updated_utc->epoch);
my $updated = $updated_local->strftime("%a %H:%M");

sub hour_to_period
{
    my $hour = shift;

    return "Night" if $hour < 6;
    return "Morning" if $hour < 12;
    return "Afternoon" if $hour < 18;
    return "Evening";
}

# Assign forecasts to pages
my %pages = ();
my @page_order = ();

my %day_frames = ();
my %page_frames = ();
my $frame_number = $first_frame_number;

my $now = localtime;

for my $forecast (@{$data->{features}->[0]->{properties}->{timeSeries}})
{
    my $time_utc = Time::Piece->strptime($forecast->{time}, "%FT%H:%MZ");
    my $forecast_day = $time_utc->fullday;

    next if $time_utc->julian_day >= $now->julian_day + 6;

    my $minute = $time_utc->min;
    my $hour = $time_utc->hour;
    my $local = localtime($time_utc->epoch);
    my $logical = localtime($local->epoch - $logical_day_start * 60 * 60);
    my $logical_day = $logical->fullday;

    $forecast->{Day} = $local->wdayname;
    $forecast->{Time} = $local->strftime("%H:%M");   

    my $forecast_page = $logical_day . " " . hour_to_period($hour);

    push @page_order, $forecast_page unless exists $pages{$forecast_page};
    push @{$pages{$forecast_page}}, $forecast;

    $day_frames{$logical_day} = $frame_number++ unless exists $day_frames{$logical_day};
    $page_frames{$forecast_page} = $day_frames{$logical_day};
}

# Apply units and suchlike to each forecast, on a page-by-page basis
# so that we can make sure there are exactly two on each page.
my %types_top = ();
my %types_bottom = ();
my %types = (
    NA => "Unknown",
    -1 => "Trace Rain",
    0 => "Clear",
    1 => "Sunny",
    2 => "Partly Cloudy",
    3 => "Partly Cloudy",
    5 => "Mist",
    6 => "Fog",
    7 => "Cloudy",
    8 => "Overcast",
    9 => "Light Showers",
    10 => "Light Showers",
    11 => "Drizzle",
    12 => "Light Rain",
    13 => "Heavy Showers",
    14 => "Heavy Showers",
    15 => "Heavy Rain",
    16 => "Sleet Showers",
    17 => "Sleet Showers",
    18 => "Sleet",
    19 => "Hail Showers",
    20 => "Hail Showers",
    21 => "Hail",
    22 => "L.Snow Showers",
    23 => "L.Snow Showers",
    24 => "Light Snow",
    25 => "H.Snow Showers",
    26 => "H.Snow Showers",
    27 => "Heavy Snow",
    28 => "Thunder Showers",
    29 => "Thunder Showers",
    30 => "Thunder",
);

my %uv = (
    0 => "N/A",
    1 => "1 Low",
    2 => "2 Low",
    3 => "3 Moderate",
    4 => "4 Moderate",
    5 => "5 Moderate",
    6 => "6 High",
    7 => "7 High",
    8 => "8 V. High",
    9 => "9 V. High",
    10 => "10 V. High",
    11 => "11 Extreme",
);

for my $type (keys %types)
{
    ($types_top{$type}, $types_bottom{$type}) = split / /, $types{$type}, 2;
}

for my $page_title (@page_order)
{
    my $max = $#{$pages{$page_title}};
    $max = 1 if $max > 1;

    for my $idx (0..$max)
    {
        my $forecast = $pages{$page_title}->[$idx];

        $forecast->{feelsLikeTemp} = int($forecast->{feelsLikeTemp} + 0.5);
        $forecast->{maxScreenAirTemp} = defined $forecast->{maxScreenAirTemp} ? int($forecast->{maxScreenAirTemp} + 0.5) : '??';
        $forecast->{screenRelativeHumidity} = int($forecast->{screenRelativeHumidity} + 0.5);
        $forecast->{windSpeed10m} = int($forecast->{windSpeed10m} * 2.2369363 + 0.5);

        $forecast->{feelsLikeTemp} .= " deg C";
        $forecast->{maxScreenAirTemp} .= " deg C";
        $forecast->{screenRelativeHumidity} .= "% RH";
        $forecast->{windSpeed10m} .= " mph";    # TODO
        $forecast->{probOfPrecipitation} .= "%";
        $forecast->{windDirectionFrom10m} = cardinal($forecast->{windDirectionFrom10m});

        $forecast->{significantWeatherTop} = $types_top{$forecast->{significantWeatherCode}} || ($forecast->{significantWeatherCode} . '[Y]?[C]');
        $forecast->{significantWeatherBottom} = $types_bottom{$forecast->{significantWeatherCode}} || "";

        $forecast->{uvText} = $uv{$forecast->{uvIndex}} || ($forecast->{uvIndex} . '[Y]?[C]');
        $forecast->{""} = "";
    }

    # Remove any excess forecasts, or add an empty one if needed.
    $#{$pages{$page_title}} = 1;
}

my %titles = (
    feelsLikeTemp => "Feels Like:",
    maxScreenAirTemp => "Temperature:",
    screenRelativeHumidity => "Humidity:",
    windSpeed10m => "Wind Speed:",
    windDirectionFrom10m => "Wind Direction:",  # TODO
    uvText => "UV Index:",
    probOfPrecipitation => "Precip. Prob'ity:",
    significantWeatherTop => "Weather Type:",
    significantWeatherBottom => "",
    "" => "",
);

sub table_line
{
    my ($field, $l, $r) = @_;

    sprintf("[W]%17.17s[C]%-10.10s %-10.10s", $titles{$field}, $l->{$field}, $r->{$field} || "");
}

# Now generate a frame for each page
my $frame = undef;
my $current_frame_num = 0;

my $last_page = $page_order[-1];

for my $page_title (@page_order)
{
    my ($l, $r) = @{$pages{$page_title}};
    my $frame_num = $page_frames{$page_title};

    # Have we changed frame numbers (day rollover)?
    if ($frame_num != $current_frame_num)
    {
        # Update previous day to point to this one as the next
        if (defined $frame)
        {
            $frame->set_route(11, $frame_num);
            $frame->write();
        }

        # Create new frame with right number
        $frame = new TelstarFrame($frame_num);
        $current_frame_num = $frame_num;
    }
    else
    {
        # No, so just add another subframe to this one
        $frame = $frame->next_subpage();
    }

    my @page = (
        "[R][n][D][Y]WEATHER:[W]$page_title",
        "",
        "",
        " Latest forecasts for Ledbury:",
        "",
        sprintf("[Y]%17s %-10.10s %-10.10s", "", $l->{Day}, $r->{Day} || ""),
        sprintf("[Y]%17s %-10.10s %-10.10s", "", $l->{Time}, $r->{Time} || ""),
        table_line("significantWeatherTop", $l, $r),
        table_line("significantWeatherBottom", $l, $r),
        table_line("", $l, $r),
        table_line("probOfPrecipitation", $l, $r),
        table_line("maxScreenAirTemp", $l, $r),
        table_line("feelsLikeTemp", $l, $r),
        table_line("windSpeed10m", $l, $r),
        table_line("windDirectionFrom10m", $l, $r),
        table_line("screenRelativeHumidity", $l, $r),
        table_line("uvText", $l, $r),
        "",
        " (Last updated $updated; contains",
        " public sector information licensed",
        " under the Open Government Licence.)",
    );

    $frame->set_route(0, 6);    # 0 back to index

    if ($page_title eq $last_page)
    {
        $frame->{"navmessage-select"} = "[R][n][W]Press[Y]_[W]or[Y]0[W]to return to index.";
        $frame->set_route(11, 6);
    }
    else
    {
        $frame->{"navmessage-select"} = "[R][n][W]Press[Y]_[W]for later,[Y]0[W]for index.";
    }

    $frame->{"navmessage-notfound"} = "[R][n][W]Not found! Press[Y]0[W]for weather index.";

    $frame->add_lines(@page);
    $frame->write();
}

# Now save the day list so the index page can update itself
my %daylist = ();
while (my ($day, $frame) = each %day_frames)
{
    $daylist{$frame} = $day;
}

if (open my $output, ">", $daylist)
{
    print $output JSON::PP->new->utf8->encode(\%daylist);
    close $output;
}
else
{
    die "Cannot open output $daylist: $!";
}