; extensions.conf
; Derived from Asterisk default by stripping out all the comment/empty lines
; and then dramatically trimming all the demo stuff!

[general]
static=yes
writeprotect=no
clearglobalvars=no

; Probably don't need this but leaving it here just in case...
; [globals]
; CONSOLE=Console/dsp				; Console interface for demo
; TRUNK=DAHDI/G2					; Trunk interface
; TRUNKMSD=1					; MSD digits to strip (usually 1 or 0)
;
; [trunklocal]
; exten => _9NXXXXXX,1,Dial(${GLOBAL(TRUNK)}/${EXTEN:${GLOBAL(TRUNKMSD)}})

[time]
exten => _X.,30000(time),NoOp(Time: ${EXTEN} ${timezone})
 same => n,Wait(0.25)
 same => n,Answer()
 same => n,Set(FUTURETIME=$[${EPOCH} + 12])
 same => n,SayUnixTime(${FUTURETIME},Zulu,HNS)
 same => n,SayPhonetic(z)
 same => n,SayUnixTime(${FUTURETIME},${timezone},HNS)
 same => n,Playback(spy-local)
 same => n,WaitUntil(${FUTURETIME})
 same => n,Playback(beep)
 same => n,Return()

[ani]
exten => _X.,40000(ani),NoOp(ANI: ${EXTEN})
 same => n,Wait(0.25)
 same => n,Answer()
 same => n,Playback(vm-from)
 same => n,SayDigits(${CALLERID(ani)})
 same => n,Wait(1.25)
 same => n,SayDigits(${CALLERID(ani)})	; playback again in case of missed digit
 same => n,Return()

 ; Inbound context for calls from EMF.  The main reminder call service is
 ; hooked up from the extensions.lua file, but this one defines some other
 ; extensions for testing purposes etc.
[emf_inbound]
 ; 'readback' just combines the time and ANI contexts above for SIP testing
exten => readback,1,Wait(2)
 same => n,Answer(0.25)
 same => n,Gosub(ani,_X.,ani)
 same => n,Gosub(time,_X.,time)
 same => n,Hangup()

; 'emflive' provides backup access to the Viewdata service via softmodem
exten => emflive,1,Set(VOLUME(TX)=2)
 same => n,Set(VOLUME(RX)=2)
 same => n,Answer(1)
 same => n,Softmodem(viewdata.microwavepizza.co.uk,8086,v(V23)ld(7)s(1)e)
 same => n,Hangup()

; 'emfdev' is similar but for the development instance
exten => emfdev,1,Set(VOLUME(TX)=2)
 same => n,Set(VOLUME(RX)=2)
 same => n,Answer(1)
 same => n,Softmodem(viewdata.microwavepizza.co.uk,8087,v(V23)ld(7)s(1)e)
 same => n,Hangup()
