[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0
external_media_address = viewdata.microwavepizza.co.uk
external_signaling_address = viewdata.microwavepizza.co.uk
local_net = 10.0.0.0/8

; Reminder call
[emf-alrm]
type=registration
outbound_auth=emf-alrm
server_uri=sip:sip.emf.camp:5060
client_uri=sip:2576@sip.emf.camp:5060
contact_user=2576

[emf-alrm]
type=auth
auth_type=userpass
#include password_emf-alrm
username=2576

[emf-alrm]
type=aor
contact=sip:sip.emf.camp:5060

[emf-alrm]
type=endpoint
context=emf_inbound
disallow=all
allow=g722,alaw,ulaw,gsm
outbound_auth=emf-alrm
aors=emf-alrm
from_user=2576
from_domain=sip.emf.camp
dtmf_mode=rfc4733

[emf-alrm]
type=identify
endpoint=emf-alrm
match=sip.emf.camp
