[general]
context=emf_inbound             ; Default context for incoming calls. Defaults to 'default'
allowoverlap=no                 ; Disable overlap dialing support. (Default is yes)
udpbindaddr=0.0.0.0             ; IP address to bind UDP listen socket to (0.0.0.0 binds to all)
tcpenable=yes                   ; Enable server for incoming TCP connections (default is no)
tcpbindaddr=0.0.0.0             ; IP address for TCP server to bind to (0.0.0.0 binds to all interfaces)
transport=tcp,udp               ; Set the default transports.  The order determines the primary default transport.
srvlookup=yes                   ; Enable DNS SRV lookups on outbound calls

allowexternaldomains=no         ; Disable INVITE and REFER to non-local domains
domain=viewdata.microwavepizza.co.uk
fromdomain=viewdata.microwavepizza.co.uk

; Network configuration - Azure VPS is behind a NAT so provide external details
localnet=10.0.0.0/8
externaddr=viewdata.microwavepizza.co.uk
; media_address=viewdata.microwavepizza.co.uk
; nat=force_rport,comedia
