#!/bin/bash

set -e

MYDIR="$(dirname $(realpath $0))"
ENVFILE="$MYDIR/emflive.env"
NEWDIR="$MYDIR/1h-frames"

# Load environment - will contain things like API keys!
. "$ENVFILE" || true

cd "$MYDIR"

[ -d "$NEWDIR" ] && rm -r "$NEWDIR"
mkdir "$NEWDIR"

# curl -o phonebook.json 'https://phones.emfcamp.org/api/phonebook/EMF2024'
# ../format-phonebook-2col --directory "$NEWDIR"

../fetch-met-office-forecast
../weather-forecast --directory "$NEWDIR"
[[ -f /tmp/live-weather-index.pid && -d /proc/$(< /tmp/live-weather-index.pid) ]] || ../weather-index --directory "$NEWDIR"

../telstar-util login "${TELSTAR_API_SERVER:?no Telstar server}" "${TELSTAR_API_USERNAME:?no Telstar username}" "${TELSTAR_API_PASSWORD:?no Telstar password}" 
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 61a "${TELSTAR_API_DATABASE:?no Telstar database}" || true
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 65a "${TELSTAR_API_DATABASE:?no Telstar database}" || true
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 66a "${TELSTAR_API_DATABASE:?no Telstar database}" || true
../telstar-util addframes "${TELSTAR_API_SERVER:?no Telstar server}" "$NEWDIR" "${TELSTAR_API_DATABASE:?no Telstar database}"
