#!/bin/bash

set -e

MYDIR="$(dirname $(realpath $0))"
ENVFILE="$MYDIR/emflive.env"
NEWDIR="$MYDIR/1h-frames"

# Load environment - will contain things like API keys!
[ -x "$ENVFILE" ] && . "$ENVFILE"

cd "$MYDIR"

[ -d "$NEWDIR" ] && rm -r "$NEWDIR"
mkdir "$NEWDIR"

curl -o phonebook.json 'https://phones.emfcamp.org/api/phonebook/EMF2024'
../format-phonebook-2col --directory "$NEWDIR"

curl -o ledbury-3hour.json "http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/json/352240?res=3hourly&key=${METOFFICE_API_KEY:?no Met Office API key}"
../weather-forecast --directory "$NEWDIR"

../telstar-util login "${TELSTAR_API_SERVER:?no Telstar server}" "${TELSTAR_API_USERNAME:?no Telstar username}" "${TELSTAR_API_PASSWORD:?no Telstar password}" 
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 61a "${TELSTAR_API_DATABASE:?no Telstar database}"
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 65a "${TELSTAR_API_DATABASE:?no Telstar database}"
../telstar-util deleteframe "${TELSTAR_API_SERVER:?no Telstar server}" 66a "${TELSTAR_API_DATABASE:?no Telstar database}"
../telstar-util addframes "${TELSTAR_API_SERVER:?no Telstar server}" "$NEWDIR" "${TELSTAR_API_DATABASE:?no Telstar database}"
